units:
  # Utility/practice PCB mk.1
  # @huntercook https://github.com/jusdisgi
  #
  # Please note this is not a keyboard!
  #


  # Spacing Variables
  # PG1316S keycaps are smaller than chocs
  # These dimensions come from: https://docs.holykeebs.com/datasheets/PG1316_1U.pdf
  pgx: 16
  pgy: 16
  # Padding Variables
  pcx: cx+2
  pcy: cy+2
  pu : u+2
  pU: U+2
  ppgx: pgx + 2
  ppgy: pgy + 2
  $default_height: 16
  $default_width: 16
points:
  zones:
    main:
      anchor.shift: [100,-200]
      columns:
        firstcol:
          key:
            column_net: D5
      rows:
        firstrow:
          key:
            row_net: D8
# Alias for left corner of board
# value: start
# $params: [start]
# $args: ["main_firstcol_firstrow"]
outlines:
  board:
    - what: polygon
      operation: stack
      points:
        - ref: main_firstcol_firstrow
          shift: [0,0]
        - ref: main_firstcol_firstrow
          shift: [0,100]
        - ref: main_firstcol_firstrow
          shift: [100,100]
        - ref: main_firstcol_firstrow
          shift: [100,0]
pcbs:
  utility_board:
    outlines:
      main:
        outline: board
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: main_firstcol_firstrow
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
            shift: [10,10]
      # diode:
      #   what: diode_smd_mmbd4148plm
      #   where: /^hand_middle/
      #   params:
      #     from1: "index_{{row}}"
      #     from2: "{{colrow}}"
      #     from3: "ring_{{row}}"
      #     from4: "inner_{{row}}"
      #     from5: "pinky_{{row}}"
      #     to: "{{row_net}}"
      #     side: F
      #   adjust:
      #     shift: [0, 2.5]
      #     rotate: 180
      # xiao:
      #     what: mcu_xiao_smd
      #     where:
      #       ref: hand_inner_top
      #       shift: [22,-3]
      #       rotate: 0
      # power:
      #   what: slider
      #   params:
      #     from: BAT_P
      #     to: BAT
      #   where:
      #     ref: thumb_far_fan
      #     shift: [7.25,14]
      #     rotate: -90
      # battcon:
      #   what: battery_connector_molex_pico_ezmate_1x02
      #   where:
      #     ref: thumb_far_fan
      #     shift: [1,11]
      #     rotate: -90