units:
  # Utility/practice PCB mk.1
  # @huntercook https://github.com/jusdisgi
  #
  # Please note this is not a keyboard!
  #


  # Spacing Variables
  # PG1316S keycaps are smaller than chocs
  # These dimensions come from: https://docs.holykeebs.com/datasheets/PG1316_1U.pdf
  pgx: 16
  pgy: 16
  # Padding Variables
  pcx: cx+2
  pcy: cy+2
  pu : u+2
  pU: U+2
  ppgx: pgx + 2
  ppgy: pgy + 2
  $default_height: 16
  $default_width: 16
points:
  zones:
    hand:
      anchor.shift: [100,-200]
      key:
        padding: 1pgy
        spread: 1pgx
      columns:
        pinky:
          key:
            column_net: P0.02
        ring:
          key:
            column_net: P0.15
        middle:
          key:
            column_net: P1.13
        index:
          key:
            column_net: P1.05
        inner:
          key:
            column_net: P1.14
      rows:
        home:
          row_net: P0.03
        top:
          row_net: P1.03
# Alias for left corner of board
# value: start
# $params: [start]
# $args: ["hand_firstcol_firstrow"]
outlines:
  board:
    - what: polygon
      operation: stack
      points:
        - ref: hand_pinky_home
          shift: [0,0]
        - ref: hand_pinky_home
          shift: [0,100]
        - ref: hand_pinky_home
          shift: [100,100]
        - ref: hand_pinky_home
          shift: [100,0]
pcbs:
  utility_board:
    outlines:
      main:
        outline: board
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
            shift: [10,10]
      diode:
        what: diode_smd_mmbd4148plm
        where: /^hand_middle/
        params:
          from1: "index_{{row}}"
          from2: "{{colrow}}"
          from3: "ring_{{row}}"
          from4: "inner_{{row}}"
          from5: "pinky_{{row}}"
          to: "{{row_net}}"
          side: F
        adjust:
          shift: [10, 12.5]
          rotate: 180
      xiao_slot_bde:
        what: util_xiao_ble_plus_cutout
        where:
          ref: hand_pinky_home
          shift: [10.6,50]
          rotate: 90
        params:
          side: F
      xiao_slot_a:
        what: util_xiao_ble_plus_cutout_simple
        where:
          ref: hand_pinky_home
          shift: [10.6,83]
          rotate: 90
        params:
          side: F
          P1: D0_a
          P2: D1_a
          P3: D2_a
          P4: D3_a
          P5: D4_a
          P6: D5_a
          P7: D6_a
          P8: D7_a
          P9: D8_a
          P10: D9_a
          P11: D10_a
          P12: 3V3_a
          P13: GND_a
          P14: 5V_a
          P15: D11_a
          P16: D12_a
          P17: D13_a
          P18: D14_a
          P19: D15_a
          P20: D16_a
          P21: D17_a
          P22: D18_a
          P23: D19_a
          P24: D20_a
          P25: D21_a
          P26: D22_a
          P27: D23_a
          P28: BAT_a
      xiao_breakout_a:
        what: xiao_ble_plus_breakout_holes
        where:
          ref: hand_pinky_home
          shift: [10.6,83]
          rotate: 0
        params:
          orientation: up
          P1: D0_a
          P2: D1_a
          P3: D2_a
          P4: D3_a
          P5: D4_a
          P6: D5_a
          P7: D6_a
          P8: D7_a
          P9: D8_a
          P10: D9_a
          P11: D10_a
          P12: 3V3_a
          P13: GND_a
          P14: 5V_a
          P15: D11_a
          P16: D12_a
          P17: D13_a
          P18: D14_a
          P19: D15_a
          P20: D16_a
          P21: D17_a
          P22: D18_a
          P23: D19_a
          P24: D20_a
          P25: D21_a
          P26: D22_a
          P27: D23_a
          P28: BAT_a


      # xiao:
      #   what: mcu_xiao_plus_smd
      #   where:
      #     ref: hand_pinky_home
      #     shift: [10.6,35]
      #     rotate: 90
      #   params:
      #     side: F

      # power:
      #   what: slider
      #   params:
      #     from: BAT_P
      #     to: BAT
      #   where:
      #     ref: thumb_far_fan
      #     shift: [7.25,14]
      #     rotate: -90
      # battcon:
      #   what: battery_connector_molex_pico_ezmate_1x02
      #   where:
      #     ref: thumb_far_fan
      #     shift: [1,11]
      #     rotate: -90